language: node_js
node_js:
  - lts/*
before_install:
  - openssl aes-256-cbc -K $encrypted_deaba444d90d_key -iv $encrypted_deaba444d90d_iv 
    -in docs_deploy_key.enc -out ./docs_deploy_key -d
install:
  - yarn global add vuepress
  - yarn

stages:
  - build
  - name: production
    if: branch = master

jobs:
  include:
    - stage: build
      script:
        - yarn build
        - echo $TRAVIS_COMMIT > src/.vuepress/dist/gitcommit.txt
        - du -ah src/.vuepress/dist
    - stage: production
      script:
        - echo "Deploying to production"
        - eval "$(ssh-agent -s)"
        - chmod 600 ./docs_deploy_key
        - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./docs_deploy_key
        - rsync -hrvz --delete -e 'ssh -i ./docs_deploy_key -o "StrictHostKeyChecking no"' src/.vuepress/dist ${SERVER_USER}@${SERVER_IP}:~/domains/docs.pupil-labs.com/html
        - echo "Production deployed"

cache: yarn

