language: node_js
node_js:
  - lts/*
install:
  - yarn global add vuepress
  - yarn
script:
  - yarn build
  - echo $TRAVIS_COMMIT > dist/gitcommit.txt
  - du -h src/.vuepress/dist
# deploy:
cache: yarn